function [Rba,M] = Rotations(in1)
%ROTATIONS
%    [RBA,M] = ROTATIONS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    31-Jan-2020 16:59:16

psi = in1(3,:);
rho = in1(1,:);
theta = in1(2,:);
t2 = cos(psi);
t3 = cos(rho);
t4 = cos(theta);
t5 = sin(psi);
t6 = sin(rho);
t7 = sin(theta);
t8 = t4.^2;
t9 = t2.*t3;
t10 = t2.*t6;
t11 = t3.*t5;
t12 = t5.*t6;
t13 = t7.*t10;
t14 = t7.*t11;
t15 = t7.*t12;
t16 = t7.*t9;
t17 = -t15;
t18 = -t16;
t19 = t10+t14;
t20 = t11+t13;
t21 = t9+t17;
t22 = t12+t18;
Rba = reshape([t2.*t4,t20,t22,-t4.*t5,t21,t19,t7,-t4.*t6,t3.*t4],[3,3]);
if nargout > 1
    M = reshape([t3.*t4.*t21+t4.*t6.*t19,-t3.*t4.*t20-t4.*t6.*t22,t19.*t20-t21.*t22,t5.*t7.^2+t3.*t8.*t11+t6.*t8.*t12,t2.*t8-t3.*t7.*t22+t6.*t7.*t20,-t4.*t9.*t19+t4.*t10.*t21+t2.*t4.*t5.*t7,-t2.*t4.*t7-t3.*t4.*t22+t4.*t6.*t20,0.0,t5.^2.*t8+t19.^2+t21.^2],[3,3]);
end
