function [W,RHS] = PendulumODEMatrices(in1,F,in3)
%PENDULUMODEMATRICES
%    [W,RHS] = PENDULUMODEMATRICES(IN1,F,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    16-May-2020 13:04:14

L = in3(3,:);
M = in3(2,:);
dtheta1 = in1(5,:);
dtheta2 = in1(6,:);
dx = in1(4,:);
g = in3(4,:);
m = in3(1,:);
theta1 = in1(2,:);
theta2 = in1(3,:);
t2 = cos(theta1);
t3 = cos(theta2);
t4 = sin(theta1);
t5 = sin(theta2);
t6 = L.^2;
t7 = -theta2;
t8 = L.*M.*t3;
t9 = t7+theta1;
t10 = L.*M.*t2.*2.0;
t11 = cos(t9);
t12 = sin(t9);
t13 = -t10;
t14 = -t8;
t15 = L.*dtheta1.*dtheta2.*t12;
t16 = M.*t6.*t11;
W = reshape([M.*2.0+m,t13,t14,t13,M.*t6.*2.0,t16,t14,t16,M.*t6],[3,3]);
if nargout > 1
    RHS = [F;-L.*M.*(-t15+g.*t4.*2.0+dtheta1.*dx.*t4.*2.0);-L.*M.*(t15+g.*t5+dtheta2.*dx.*t5)];
end
