function [W,RHS] = BallAndBeamODEMatrices(in1,To,in3)
%BALLANDBEAMODEMATRICES
%    [W,RHS] = BALLANDBEAMODEMATRICES(IN1,TO,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    16-Feb-2020 20:45:12

J = in3(1,:);
M = in3(2,:);
R = in3(3,:);
dtheta = in1(4,:);
g = in3(4,:);
theta = in1(2,:);
x = in1(1,:);
W = reshape([(M.*(R.*5.0+2.0))./(R.*5.0),0.0,0.0,J+(M.*(R.*2.0+R.^2.*5.0+x.^2.*5.0))./5.0],[2,2]);
if nargout > 1
    t2 = sin(theta);
    RHS = [M.*(g.*t2-dtheta.^2.*x);To+M.*g.*(R.*t2+x.*cos(theta))];
end
