function p = BallPosition(in1,in2)
%BALLPOSITION
%    P = BALLPOSITION(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    16-Feb-2020 20:45:12

R = in2(3,:);
theta = in1(2,:);
x = in1(1,:);
t2 = cos(theta);
t3 = sin(theta);
p = [-R.*t3+t2.*x;0.0;R.*t2+t3.*x];
